"""Official parcel identifiers: ULPIN as identity, DIGIPIN as navigation.

Three identifiers, three distinct roles, never confused:

- **ULPIN** (Unique Land Parcel Identification Number, "Bhu-Aadhaar",
  DILRMP): the 14-character official *identity* of a parcel. This is
  what records and notices cite. Validated here; issued by the state's
  land records department, never generated by this platform.
- **DIGIPIN** (India Post digital address grid): a 10-symbol geocode of
  a ~3.8 m grid cell, useful for *navigating a field inspector to the
  ground* ("go to 39J-49L-L8T4"). It names a location, not a parcel —
  parcels move under resurvey, DIGIPINs never do — so it is a
  navigation aid only and carries no legal weight here.
- **Geometry** (the PostGIS multipolygon on the parcel record) remains
  the legal authority on extent. Identifiers point at the parcel; the
  geometry *is* the parcel.

DIGIPIN codec implements the Department of Posts specification: the
bounding box (2.5–38.5°N, 63.5–99.5°E) is divided 4×4 recursively ten
times over the official symbol grid, hyphenated 3-3-4.
"""

import re
from typing import Any

ULPIN_LENGTH = 14
_ULPIN_PATTERN = re.compile(r"^[A-Z0-9]{14}$")

# Department of Posts DIGIPIN symbol grid, row 0 = northernmost band.
_DIGIPIN_GRID = (
    ("F", "C", "9", "8"),
    ("J", "3", "2", "7"),
    ("K", "4", "5", "6"),
    ("L", "M", "P", "T"),
)
_DIGIPIN_INDEX = {
    symbol: (row, col)
    for row, band in enumerate(_DIGIPIN_GRID)
    for col, symbol in enumerate(band)
}
_MIN_LAT, _MAX_LAT = 2.5, 38.5
_MIN_LON, _MAX_LON = 63.5, 99.5
_LEVELS = 10


def validate_ulpin(value: str) -> str:
    """Return the ULPIN if structurally valid, else raise ValueError.

    Structural check only (14 uppercase alphanumerics per DILRMP);
    whether it is *issued* is the land records department's authority.
    """
    if not _ULPIN_PATTERN.fullmatch(value):
        raise ValueError(
            f"invalid ULPIN {value!r}: expected {ULPIN_LENGTH} uppercase "
            "alphanumeric characters"
        )
    return value


def is_valid_ulpin(value: str | None) -> bool:
    return value is not None and _ULPIN_PATTERN.fullmatch(value) is not None


def encode_digipin(lat: float, lon: float) -> str:
    """Encode a WGS84 coordinate to a DIGIPIN (XXX-XXX-XXXX)."""
    if not (_MIN_LAT <= lat <= _MAX_LAT and _MIN_LON <= lon <= _MAX_LON):
        raise ValueError(
            f"coordinate ({lat}, {lon}) is outside the DIGIPIN bounding box"
        )
    min_lat, max_lat = _MIN_LAT, _MAX_LAT
    min_lon, max_lon = _MIN_LON, _MAX_LON
    symbols: list[str] = []
    for _ in range(_LEVELS):
        lat_div = (max_lat - min_lat) / 4
        lon_div = (max_lon - min_lon) / 4
        row = min(int((max_lat - lat) / lat_div), 3)  # 0 = northernmost band
        col = min(int((lon - min_lon) / lon_div), 3)
        symbols.append(_DIGIPIN_GRID[row][col])
        max_lat -= row * lat_div
        min_lat = max_lat - lat_div
        min_lon += col * lon_div
        max_lon = min_lon + lon_div
    code = "".join(symbols)
    return f"{code[:3]}-{code[3:6]}-{code[6:]}"


def decode_digipin(code: str) -> tuple[float, float]:
    """Decode a DIGIPIN to the center (lat, lon) of its ~3.8 m cell."""
    symbols = code.replace("-", "").upper()
    if len(symbols) != _LEVELS or any(s not in _DIGIPIN_INDEX for s in symbols):
        raise ValueError(f"invalid DIGIPIN {code!r}")
    min_lat, max_lat = _MIN_LAT, _MAX_LAT
    min_lon, max_lon = _MIN_LON, _MAX_LON
    for symbol in symbols:
        row, col = _DIGIPIN_INDEX[symbol]
        lat_div = (max_lat - min_lat) / 4
        lon_div = (max_lon - min_lon) / 4
        max_lat -= row * lat_div
        min_lat = max_lat - lat_div
        min_lon += col * lon_div
        max_lon = min_lon + lon_div
    return ((min_lat + max_lat) / 2, (min_lon + max_lon) / 2)


def identifier_block(parcel: dict[str, Any]) -> dict[str, Any]:
    """The identifier section for records and notices.

    ULPIN leads when present and valid; survey number is the fallback
    citation; DIGIPIN is computed from the geometry's representative
    point for field navigation. The authority line is part of the
    block on purpose — every consumer repeats it, none forgets it.
    """
    from shapely.geometry import shape

    ulpin = parcel.get("ulpin")
    ulpin_ok = is_valid_ulpin(ulpin)
    point = shape(parcel["geometry"]).representative_point()
    try:
        digipin = encode_digipin(point.y, point.x)
    except ValueError:
        digipin = None
    return {
        "official_identifier": (
            {"scheme": "ULPIN", "value": ulpin}
            if ulpin_ok
            else {"scheme": "survey_no", "value": parcel.get("survey_no")}
        ),
        "ulpin": ulpin if ulpin_ok else None,
        "survey_no": parcel.get("survey_no"),
        "digipin": digipin,
        "authority_note": (
            "Identifiers cite the parcel; the recorded parcel geometry is the "
            "legal authority on extent. DIGIPIN is a navigation aid only."
        ),
    }
